[images]
  remote_images = ["https://images.unsplash.com/.*", "https://efoodorder.netlify.app/.*" ]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "functions/"